name: Build Thesis PDF

on:
  push:
    paths:
      - '**.tex'
      - '**.bib'
      - '.github/workflows/build-thesis.yml'
      - 'Makefile'
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install TeX Live
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            texlive-latex-extra \
            latexmk \
            biber \
            texlive-bibtex-extra \
            texlive-fonts-recommended \
            texlive-lang-english

      - name: Compile thesis
        run: |
          cd thesis
          latexmk -pdf -interaction=nonstopmode -synctex=1 \
            -file-line-error -outdir=build -jobname=thesis main.tex

      - name: Upload PDF
        uses: actions/upload-artifact@v4
        with:
          name: thesis-pdf
          path: thesis/build/thesis.pdf